# Site settings
title: Japaniku
email: palmercluff@gmail.com
description: "A Blog About Traveling, Japan, and Everything In Between!"
baseurl: ""
url: "http://japaniku.com"
twitter_username: ya_boi_palmer
github_username:  palmercluff

# Build settings
markdown: kramdown
permalink: pretty
